server:
  port: 8080
  bind-address: "0.0.0.0"
db:
  source: jdbc
  connection:
    url: jdbc:h2:tcp://localhost:8080/h2
    poolName: h2
statements:
  # Create database schema
  create-artefact: "CREATE TABLE ARTEFACT (id SERIAL PRIMARY KEY, addDate DATE DEFAULT NOW() )"
  create-hash: "CREATE TABLE HASH (idHash SERIAL PRIMARY KEY, hashValue INT, file VARCHAR(255),
                    line INT, id INT, FOREIGN KEY (int) REFERENCES Artefact(id) )"
  create-clone: "CREATE TABLE CLONE (idClone SERIAL PRIMARY KEY, 
                    idHash1 INT, idHash2 INT,
                    FOREIGN KEY (idHash2) REFERENCES Hash(idHash), FOREIGN KEY (idHash2) REFERENCES Hash(idHash)"
  # Select all the clones
  select-all-clones: "SELECT * FROM CLONE"
