server:
  port: 8080
  bind-address: "0.0.0.0"
db:
  source: jdbc
  connection:
    username: "agnetti-saidi"
    password: "marc_soumeya"
    url: "jdbc:h2:@localhost:8080/h2"
    poolName: h2
    initializationFailTimeout: -1
    connectionTimeout: 2000
  statements:
    drop-tables: "drop table if exists ARTEFACT cascade"
    # Create database schema
    create-artefact: "CREATE TABLE ARTEFACT (id SERIAL PRIMARY KEY, addDate DATE DEFAULT NOW(),
                      groupId VARCHAR (255) )"
    create-hash: "CREATE TABLE HASH (idHash SERIAL PRIMARY KEY, hashValue INT, file VARCHAR(255),
                      line INT, id INT, FOREIGN KEY (int) REFERENCES Artefact(id) )"
    create-clone: "CREATE TABLE CLONE (idClone SERIAL PRIMARY KEY, 
                      idHash1 INT, idHash2 INT,
                      FOREIGN KEY (idHash2) REFERENCES Hash(idHash), FOREIGN KEY (idHash2) REFERENCES Hash(idHash)"
    #insert statements
    insert-artefact: "INSERT INTO ARTEFACT (groupId) VALUES (?) RETURNING id"
    insert-clone: "INSERT INTO CLONE (idHash1, idHash2) VALUES (?, ?) "
    # Select statements
    select-all-artefact: "SELECT * FROM ARTEFACT"
    select-all-clones: "SELECT * FROM CLONE"
