openapi: 3.0.3
info:
  title: Clone War
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: "Local server"

paths:
  "/artefacts":
    get:
      description: Returns all the artifacts
      responses:
        '200':
          description: A list of pets.

  "/artefacts/{id}":
    get:
      description: Returns all pets from the system that the user has access to
      responses:
        '200':
          description: A list of pets.
      parameters:
        - name: id
          in: path
          description: The id of a specific artifact
          required: true
          schema:
            type: integer
            format: int32


  "/clones/{id}":
    get:
      description: Returns all pets from the system that the user has access to
      parameters:
        - name: id
          in: path
          description: The id of a specific artifact
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of pets.

  "/scores/{id}":
    get:
      description: Returns all pets from the system that the user has access to
      responses:
        '200':
          description: A list of pets.
      parameters:
        - name: id
          in: path
          description: The id of a specific artifact
          required: true
          schema:
            type: integer
            format: int32
  "/allscores":
    get:
      description: Returns all pets from the system that the user has access to
      responses:
        '200':
          description: A list of pets.


