server:
  port: 8080
  bind-address: "0.0.0.0"

db:
  source: jdbc
  connection:
    username: sa
    password:
    url: "jdbc:h2:./src/main/resources/clone"
    poolName: clone
    initializationFailTimeout: -1
    connectionTimeout: 2000

  statements:
    # Ping statement
    ping: "SET @HELIDON_PING=0"
    # Create database schema
    create-types: "CREATE TABLE TEST (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL)"
    select-all-types: "SELECT * FROM TEST"
    insert-type: "INSERT INTO TEST VALUES(?, ?)"
